bookstor/urls.py
9*"""bookstor URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/3.2/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  path('', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  path('', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.urls import include, path
    2. Add a URL to urlpatterns:  path('blog/', include('blog.urls'))
"""
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
	path('', include('main.urls')),
    path('admin/', admin.site.urls),
	# path('accounts/', include('django.contrib.auth.urls')),
	path('users/', include('user.urls')),
]

main/urls.py
from django.urls import path
from . import views

urlpatterns = [
	# path('', views.index, name='index'),
	
	path('', views.BooksListView.as_view(), name='index'),
	path('book/<int:pk>', views.BookDetailView.as_view(), name='book'),
	path('book/create', views.BookCreateView.as_view(), name='book_create'),
	path('book/create2', views.create_book, name='book_create2'),

	path('authors/', views.AuthorsListView.as_view(), name='authors'),
	path('author/<int:pk>', views.AuthorDetailView.as_view(), name='author'),
	path('author/create', views.AuthorCreateView.as_view(), name='author_create'),
	path('author/<int:pk>/update', views.AuthorUpdateView.as_view(), name='author_updeate'),
	path('author/<int:pk>/delete', views.AuthorDeleteView.as_view(), name='author_delete'),

	path('categories/', views.CategoriesListView.as_view(), name='categories'),
	path('catigory/create', views.CatigoryCreateView.as_view(), name='catigory_create'),


]

main/models.py
from django.urls import reverse
from tabnanny import verbose
from django.db import models
from django.contrib.auth.models import User

class Book(models.Model):
	title = models.CharField(max_length=200, verbose_name='Название')
	description = models.TextField(verbose_name='Описание')
	isbn = models.CharField(max_length=13)
	# img = models.ImageField()

	create_at = models.DateTimeField(auto_now_add=True)
	update_at = models.DateTimeField(auto_now=True)

	catigory = models.ManyToManyField('Catigory', verbose_name='Категория')
	author = models.ManyToManyField('Author', verbose_name='Автор')

	added_at = models.ForeignKey(User, null=True, on_delete=models.CASCADE)

	def get_absolute_url(self):
		return reverse('book', args=[str(self.pk)])

	def __str__(self) :
		return self.title

	class Meta:
		verbose_name = 'Книга'
		verbose_name_plural = 'Книги'


class Catigory(models.Model):
	name = models.CharField(max_length=200, verbose_name='Название')

	def __str__(self) :
		return self.name
	
	class Meta:
		verbose_name = 'Категория'
		verbose_name_plural = 'Категории'


class Author(models.Model):
	first_name = models.CharField(max_length=100, verbose_name='Имя')
	last_name = models.CharField(max_length=100, verbose_name='Фамилия')

	# photo = models.ImageField()

	def get_absolute_url(self):
		return reverse('author', args=[str(self.pk)])

	def __str__(self) :
		return '{0} {1}'.format(self.last_name, self.first_name)

	class Meta:
		verbose_name = 'Автор'
		verbose_name_plural = 'Авторы'

templates/layout.html
{% load static %}
{% load addclass %}

<!DOCTYPE html>
<html lang="en">

<head>
	<meta charset="UTF-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	
	<link rel="stylesheet" href={% static 'main/bootstrap/css/bootstrap.min.css' %}>
	<link rel="stylesheet" href={% static 'main/style.css' %}>
	
	<script src={% static 'main/bootstrap/js/bootstrap.min.js' %}></script>
	<script src={% static 'main/jquery-3.6.0.min.js' %}></script>

	{% block js %}
	{% endblock %}
	
	<title>Bookstor</title>
</head>

<body>
	<nav class="navbar navbar-expand-sm navbar-dark bg-primary">
		<div class="container-fluid">
			<a class="navbar-brand" href="{% url 'index' %}">Bookstor</a>
			<button class="navbar-toggler" type="button" data-bs-toggle="collapse"
				data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false"
				aria-label="Toggle navigation">
				<span class="navbar-toggler-icon"></span>
			</button>

			<div class="collapse navbar-collapse" id="navbarSupportedContent">
				<ul class="navbar-nav me-auto mb-2 mb-sm-0">
					<li class="nav-item">
						<a class="nav-link" href="{% url 'index' %}">Главная</a>
					</li>
					{% if perms.auth.add_book %}
					<li class="nav-item">
						<a class="nav-link" href="{% url 'book_create' %}">Добавить книгу</a>
					</li>
					{% endif %}
					<li class="nav-item">
						<a class="nav-link" href="{% url 'categories' %}">Категории</a>
					</li>
					<li class="nav-item">
						<a class="nav-link" href="{% url 'authors' %}">Авторы</a>
					</li>
					<li class="nav-item">
						<a class="nav-link" href="{% url 'users' %}">Пользователи</a>
					</li>
					{% if user.is_authenticated %}
					<li class="nav-item  dropdown">
						<a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button"
							data-bs-toggle="dropdown" aria-expanded="false">
							{{ user.get_username }}
						</a>
						<ul class="dropdown-menu" aria-labelledby="navbarDropdown">
							<li><a class="dropdown-item" href="{% url 'logout' %}?next={{request.path}}">Выйте</a></li>
						</ul>
					</li>
					{% else %}
					<li class="nav-item">
						<a class="nav-link" href="{% url 'login' %}">Войти</a>
					</li>
					{% endif %}
				</ul>
			</div>
		</div>
	</nav>

	<div class="container">
		{% block contant %}
		{% endblock %}
	</div>
</body>

</html>