bookstor/urls.py
9*"""bookstor URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/3.2/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  path('', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  path('', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.urls import include, path
    2. Add a URL to urlpatterns:  path('blog/', include('blog.urls'))
"""
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
	path('', include('main.urls')),
    path('admin/', admin.site.urls),
	# path('accounts/', include('django.contrib.auth.urls')),
	path('users/', include('user.urls')),
]

main/urls.py
from django.urls import path
from . import views

urlpatterns = [
	# path('', views.index, name='index'),
	
	path('', views.BooksListView.as_view(), name='index'),
	path('book/<int:pk>', views.BookDetailView.as_view(), name='book'),
	path('book/create', views.BookCreateView.as_view(), name='book_create'),
	path('book/create2', views.create_book, name='book_create2'),

	path('authors/', views.AuthorsListView.as_view(), name='authors'),
	path('author/<int:pk>', views.AuthorDetailView.as_view(), name='author'),
	path('author/create', views.AuthorCreateView.as_view(), name='author_create'),
	path('author/<int:pk>/update', views.AuthorUpdateView.as_view(), name='author_updeate'),
	path('author/<int:pk>/delete', views.AuthorDeleteView.as_view(), name='author_delete'),

	path('categories/', views.CategoriesListView.as_view(), name='categories'),
	path('catigory/create', views.CatigoryCreateView.as_view(), name='catigory_create'),


]

main/models.py
from django.urls import reverse
from tabnanny import verbose
from django.db import models
from django.contrib.auth.models import User

class Book(models.Model):
	title = models.CharField(max_length=200, verbose_name='Название')
	description = models.TextField(verbose_name='Описание')
	isbn = models.CharField(max_length=13)
	# img = models.ImageField()

	create_at = models.DateTimeField(auto_now_add=True)
	update_at = models.DateTimeField(auto_now=True)

	catigory = models.ManyToManyField('Catigory', verbose_name='Категория')
	author = models.ManyToManyField('Author', verbose_name='Автор')

	added_at = models.ForeignKey(User, null=True, on_delete=models.CASCADE)

	def get_absolute_url(self):
		return reverse('book', args=[str(self.pk)])

	def __str__(self) :
		return self.title

	class Meta:
		verbose_name = 'Книга'
		verbose_name_plural = 'Книги'


class Catigory(models.Model):
	name = models.CharField(max_length=200, verbose_name='Название')

	def __str__(self) :
		return self.name
	
	class Meta:
		verbose_name = 'Категория'
		verbose_name_plural = 'Категории'


class Author(models.Model):
	first_name = models.CharField(max_length=100, verbose_name='Имя')
	last_name = models.CharField(max_length=100, verbose_name='Фамилия')

	# photo = models.ImageField()

	def get_absolute_url(self):
		return reverse('author', args=[str(self.pk)])

	def __str__(self) :
		return '{0} {1}'.format(self.last_name, self.first_name)

	class Meta:
		verbose_name = 'Автор'
		verbose_name_plural = 'Авторы'

main/forms.py
from django.forms import ModelForm, TextInput, Textarea, SelectMultiple
from .models import Book

class BookCreateForm(ModelForm):
	class Meta:
		model = Book
		fields = ['title', 'description', 'isbn', 'catigory', 'author']
		
		widgets = {
			'title': TextInput(attrs={'class': 'form-control'}),
			'description': Textarea(attrs={'class': 'form-control'}),
			'isbn': TextInput(attrs={'class': 'form-control'}),
			'catigory': SelectMultiple(attrs={'class': 'form-control'}),
			'author': SelectMultiple(attrs={'class': 'form-control'}),
		}

main/forms/book.py
from django.forms import ModelForm, TextInput, Textarea, SelectMultiple
from ..models import Book

class BookCreateForm(ModelForm):
	class Meta:
		model = Book
		fields = ['title', 'description', 'isbn', 'catigory', 'author']
		
		widgets = {
			'title': TextInput(attrs={'class': 'form-control'}),
			'description': Textarea(attrs={'class': 'form-control'}),
			'isbn': TextInput(attrs={'class': 'form-control'}),
			'catigory': SelectMultiple(attrs={'class': 'form-control'}),
			'author': SelectMultiple(attrs={'class': 'form-control'}),
		}

main/forms/catigory.py
from django.forms import ModelForm, TextInput
from ..models import Catigory

class CatigoryCreateForm(ModelForm):
	class Meta:
		model = Catigory
		fields = ['name']
		
		widgets = {
			'name': TextInput(attrs={'class': 'form-control'}),
		}

main/views.py
from django import template
from django.shortcuts import render
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import ListView, DetailView
from django.views.generic.edit import CreateView
from django.shortcuts import redirect 
from .models import Author, Book
from .forms import BookCreateForm


class BooksListView(LoginRequiredMixin, ListView):
	model = Book
	# queryset = Book.objects.filter(title__icontains='war')[:5]
	template_name = 'main/books.html'
	context_object_name = 'books'
	paginate_by = 500

class BookDetailView(LoginRequiredMixin, DetailView):
	model = Book
	template_name = 'main/book.html'
	context_object_name = 'book'

class BookCreateView(LoginRequiredMixin, CreateView):
	model = Book
	# model.added_at = 
	template_name = 'main/book_create.html'
	form_class = BookCreateForm
	def form_valid(self, form):
		form.instance.added_at = self.request.user
		return super().form_valid(form)


class AuthorsListView(LoginRequiredMixin, ListView):
	model = Author
	template_name = 'main/authors.html'
	context_object_name = 'authors'

class AuthorDetailView(LoginRequiredMixin, DetailView):
	model = Author
	template_name = 'main/author.html'
	context_object_name = 'author'

class AuthorCreateView(LoginRequiredMixin, CreateView):
	model = Author
	template_name = 'main/author_edit.html'
	fields = ['first_name', 'last_name']
	# form_class = UnitForm

# class AuthorUpdateView(LoginRequiredMixin, UpdateView):
# 	model = User
# 	template_name = 'user/edit.html'
# 	form_class = UserUpdateForm
# 	success_url = '/users'
# 	# fields = ['username', 'groups']
# 	# form_class = UnitForm
	
# class AuthorDeleteView(DeleteView):
# 	model = User
# 	template_name = 'user/delete.html'
# 	success_url = '/users'
# 	context_object_name = 'unit'

main/views/author.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView
from ..models import Author


class AuthorsListView(LoginRequiredMixin, ListView):
	model = Author
	template_name = 'main/authors.html'
	context_object_name = 'authors'

class AuthorDetailView(LoginRequiredMixin, DetailView):
	model = Author
	template_name = 'main/author.html'
	context_object_name = 'author'

class AuthorCreateView(LoginRequiredMixin, CreateView):
	model = Author
	template_name = 'main/author_edit.html'
	fields = ['first_name', 'last_name']
	# form_class = UnitForm

class AuthorUpdateView(LoginRequiredMixin, UpdateView):
	pass
# 	model = User
# 	template_name = 'user/edit.html'
# 	form_class = UserUpdateForm
# 	success_url = '/users'
# 	# fields = ['username', 'groups']
# 	# form_class = UnitForm
	
class AuthorDeleteView(DeleteView):
	pass
# 	model = User
# 	template_name = 'user/delete.html'
# 	success_url = '/users'
# 	context_object_name = 'unit'

main/views/book.py
from django.shortcuts import render

from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import ListView, DetailView, CreateView

from ..models import Book
from ..forms import BookCreateForm


class BooksListView(LoginRequiredMixin, ListView):
	model = Book
	# queryset = Book.objects.filter(title__icontains='war')[:5]
	template_name = 'main/books.html'
	context_object_name = 'books'
	paginate_by = 500

class BookDetailView(LoginRequiredMixin, DetailView):
	model = Book
	template_name = 'main/book.html'
	context_object_name = 'book'

class BookCreateView(LoginRequiredMixin, CreateView):
	model = Book
	# model.added_at = 
	template_name = 'main/book_create.html'
	form_class = BookCreateForm
	def form_valid(self, form):
		form.instance.added_at = self.request.user
		return super().form_valid(form)
		
def create_book(request):
	if request.method == "POST":
		# book = Book()
		# book.title = request.POST.get("name")
		# dir(request.POST)
		# print(request.POST.get("title"))
		# print(dir(request.POST))
		print(request.POST.getlist())
		return render(request, "main/book_create2.html")
	else:
		return render(request, "main/book_create2.html")

main/views/catigory.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import ListView, CreateView
from ..models import Catigory
from ..forms import CatigoryCreateForm

class CategoriesListView(LoginRequiredMixin, ListView):
	model = Catigory
	template_name = 'main/categories.html'
	context_object_name = 'categories'

class CatigoryCreateView(LoginRequiredMixin, CreateView):
	model = Catigory
	template_name = 'main/catigory_create.html'
	form_class = CatigoryCreateForm
	success_url = '/'

main/templates/main/author.html
{% extends "layout.html" %}

{% block contant %}
<div class="btn-group" role="group">
	<a class="btn btn-outline-primary" href="{% url 'author_updeate' author.id  %}">Изменить</a>
	<a class="btn btn-outline-primary" href="{% url 'author_delete' author.id  %}">Удалить</a>
</div>

<h1>{{ author }}</h1>

{% for book in author.book_set.all %}
<div class="card" style="width: 18rem;">
	<div class="card-body">
	  <h5 class="card-title">{{ book.title }}</h5>
	  <h6 class="card-subtitle mb-2 text-muted">
		{% for author in book.author.all %}
		<a href="{% url 'author' author.id %}" >{{ author }}</a>
		{% endfor %}
	</h6>
	  <p class="card-text">{{ book.description }}</p>
	  <a href="{% url 'book' book.id %}" class="btn btn-primary">Подробнее</a>
	</div>
  </div>
{% endfor %}

{% endblock %}

main/templates/main/author_edit.html
{% extends "layout.html" %}

{% block contant %}
<form action="" method="post">{% csrf_token %}
	{{ form.as_p }}
	<input type="submit" value="Save" />
  </form>
{% endblock %}

main/templates/main/authors.html
{% extends "layout.html" %}

{% block contant %}
<h1>Авторы</h1>
<p>
	<a class="btn btn-outline-primary" href="{% url 'author_create' %}">Создать</a>
</p>
{% for author in authors %}
<div>
	<a href="{% url 'author' author.id %}"> {{ author.last_name }}  {{ author.first_name }} </a>
</div>
{% endfor %}

{% endblock %}

main/templates/main/book.html
{% extends "layout.html" %}

{% block contant %}
<h1>{{ book.title }}</h1>
<h6>
{% for author in book.author.all %}
<a href="{% url 'author' author.id %}" >{{ author }}</a>
{% endfor %}
</h6>
<div>
	{{ book.description }}
</div>
<div>
	<strong> Обнавлено: </strong> {{ book.update_at }}
	<br/>
	<strong> Создано: </strong> {{ book.create_at }}
	<br/>
	<strong> Добавил: </strong> {{ book.added_at }}
</div>
{% endblock %}

main/templates/main/book_create.html
{% extends "layout.html" %}

{% block contant %}

<h1>Добавить книгу</h1>

<form action="" method="post">
	{% csrf_token %}
	{{ form.as_p }}
	<input class="btn btn-primary" type="submit" value="Save" />
</form>

{% endblock %}

main/templates/main/book_create2.html
{% extends "layout.html" %}

{% block js %}
<script type="text/javascript">

</script>
{% endblock %}


{% block contant %}

<h1>Добавить книгу</h1>

<form action="" method="post">
	{% csrf_token %}
	
	<input type="text" name="title">
	<textarea name="description"></textarea>
	<input type="text" name="isbn">
	
	<div id="author">
		
	</div>
	<a href="#">Добавить автора</a>

	<div id="сatigory">
		
	</div>
	<a href="#">Добавить категорию</a>
	
	
	<!-- <input type="hidden" value="111" name="v1"> -->
	
	<input class="btn btn-primary" type="submit" value="Добавить" />
</form>

{% endblock %}

main/templates/main/books.html
{% extends "layout.html" %}

{% block contant %}
<div class="row row-cols-1 row-cols-md-3 g-4">
	{% for book in books %}
	<div class="col">
		<div class="card">
			<div class="card-header">
				<h5>{{ book.title }}</h5>
			</div>
			<div class="card-body">
				<h6 class="card-subtitle mb-2 text-muted">
					{% for author in book.author.all %}
					<a href="{% url 'author' author.id %}">{{ author }}</a>
					{% endfor %}
				</h6>
				<p class="card-text">{{ book.description }}</p>
				<a href="{% url 'book' book.id %}" class="btn btn-primary">Подробнее</a>
			</div>
		</div>
	</div>
	{% endfor %}
</div>
{% endblock %}

main/templates/main/categories.html
{% extends "layout.html" %}

{% block contant %}
<h1>Категории</h1>
<p>
	<a class="btn btn-outline-primary" href="{% url 'catigory_create' %}">Создать</a>
</p>
<table class="table table-hover">
	<tbody>
		{% for category in categories %}
		<tr>
			<td>{{ category.name }}</td>
			<td><a href="#">Изменит</a></td>
			<td><a href="#">Удалить</a></td>
		</tr>
		{% endfor %}
	</tbody>
</table>
{% endblock %}

main/templates/main/catigory_create.html
{% extends "layout.html" %}

{% block contant %}
<h1>Создать категорию</h1>
<form action="" method="post">
	{% csrf_token %}
	{{ form.as_p }}
	<input class="btn btn-primary" type="submit" value="Создать" />
</form>
{% endblock %}

main/templates/main/index.html
{% extends "layout.html" %}

{% block contant %}

{% for book in books %}
<div class="card" style="width: 18rem;">
	<div class="card-body">
		<h5 class="card-title">{{ book.title }}</h5>
		<h6 class="card-subtitle mb-2 text-muted">
			{% for author in book.author.all %}
			<a href="{% url 'author' author.id %}">{{ author }}</a>
			{% endfor %}
		</h6>
		<p class="card-text">{{ book.description }}</p>
		<a href="{% url 'book' book.id %}" class="btn btn-primary">Подробнее</a>
	</div>
</div>
{% endfor %}

{% endblock %}

main/templates/main/layout.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
	<meta charset="UTF-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<link rel="stylesheet" href={% static 'main/bootstrap/css/bootstrap.min.css' %}>
	<script src={% static 'main/bootstrap/js/bootstrap.min.js' %}></script>
	<title>Bookstor</title>
</head>

<body>
	<nav class="navbar navbar-expand-sm navbar-dark bg-primary">
		<div class="container-fluid">
			<a class="navbar-brand" href="{% url 'index' %}">Bookstor</a>
			<button class="navbar-toggler" type="button" data-bs-toggle="collapse"
				data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false"
				aria-label="Toggle navigation">
				<span class="navbar-toggler-icon"></span>
			</button>

			<div class="collapse navbar-collapse" id="navbarSupportedContent">
				<ul class="navbar-nav me-auto mb-2 mb-sm-0">
					<li class="nav-item">
						<a class="nav-link" href="{% url 'index' %}">Главная</a>
					</li>
				</ul>
			</div>
		</div>
	</nav>

	<div class="content">
		{% block contant %}
		{% endblock %}
	</div>
</body>

</html>